version : '2'
services:

  learn2:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/vol/development
    depends_on:
      - mysql

  mysql:
    image: docker.io/mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    restart: always

